Controllers/CarStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nhom2_WebsiteBanXe.Models;
using PagedList;

namespace Nhom2_WebsiteBanXe.Controllers
{
    public class CarStoreController : Controller
    {
        DataClasses1DataContext data = new DataClasses1DataContext();



        private List<Xe> Layxemoi(int count)
        {
            //sắp xếp xe cập nhật theo ngay(Ngaynhap) top 6
            return data.Xes.OrderByDescending(a => a.NgayNhap).Take(count).ToList();
        }
        public ActionResult Index(int? page)
        {
            int pageSize = 9; //số xe mới cập nhật hiện lên trang index
            int pageNum = (page ?? 1); //tạo biến số trang

            var xemoi = Layxemoi(18); //tổng số xe hiện lên trong phần chia trang
            return View(xemoi.ToPagedList(pageNum, pageSize));
        }

        //tin tức
        public ActionResult IndexTinTuc()
        {
            var tt = (from t in data.TinTucs select t).ToList();
            return View(tt);
        }
        public ActionResult ChiTietTT(int id)
        {
            var tt = from t in data.TinTucs where t.idTT == id select t;
            return View(tt.Single());
        }
        //truyền các thể loại tin lên trang index tin tức
        public ActionResult Theloaitin()
        {
            var theloaitin = from tt in data.TheLoaiTins select tt;
            return PartialView(theloaitin);
        }
        //Lấy theo loại tin tức
        public ActionResult TinTheoLoai(int id)
        {
            var tin = from tt in data.TinTucs where tt.idLoai == id select tt;
            return View(tin);
        }
        //----------------------------------------------------------//

        //lấy tất cả xe trong table       
        public ActionResult Sanpham(int? page)
        {
            int pageSize = 9;
            int pageNum = (page ?? 1);

            var xe = (from s in data.Xes select s).ToList();
            return View(xe.ToPagedList(pageNum, pageSize));
        }
        //

        
        //truyền các loại xe lên trang index
        public ActionResult Cacloaixe()
        {
            var loaixe = from tt in data.LoaiXes select tt;
            return PartialView(loaixe);
        }
        //truyền các hãng xe lên trang index
        public ActionResult Hangxe()
        {
            var hangxe = from hx in data.HangXes select hx;
            return PartialView(hangxe);
        }

        
        //Lấy xe theo loại
        public ActionResult SpTheoLoai(int id)
        {
            var xe = from tt in data.Xes where tt.idLoaiXe == id select tt;
            return View(xe);
        }
        //Lấy xe theo hãng
        public ActionResult SpTheoHang(int id)
        {
            var xe = from tt in data.Xes where tt.idHangXe == id select tt;
            return View(xe);
        }

        //thông tin chi tiết xe
        public ActionResult Details(int id)
        {
            var xe = from tt in data.Xes where tt.idXe == id select tt;
            return View(xe.Single());
        }

        public ActionResult Contact()
        {
            if(Session["TaiKhoan"] ==null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Dangnhap", "KhachHang");
            }
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Contact(FormCollection collection)
        {
            LienHe lh = new LienHe();
            KhachHang kh = (KhachHang)Session["TaiKhoan"];
            var hoten = collection["HoTen"];
            var email = collection["eMail"];
            var tieude = collection["NoiDung"];
            var noidunglh = collection["NoiDung"];

            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Vui lòng nhập họ và tên!";
            }
            else if (String.IsNullOrEmpty(tieude))
            {
                ViewData["Loi2"] = "Vui lòng nhập tiêu đề!";
            }
            else if (String.IsNullOrEmpty(noidunglh))
            {
                ViewData["Loi2"] = "Vui lòng nhập nội dung!";
            }
            else
            {
                lh.id = kh.MaKH;
                lh.NoiDung = noidunglh;
                lh.HoTen = hoten;
                lh.eMail = email;
                lh.TieuDe = tieude;
                if (ModelState.IsValid)
                {
                    data.LienHes.InsertOnSubmit(lh);
                    data.SubmitChanges();
                }
                return RedirectToAction("Index");
            }
            return this.Contact();
        }

        public ActionResult AboutUs()
        {
            return View();
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/LTW.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="~/Content/assets/images/icons/favicon.ico" />
    <title>Trang quản trị Admin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body style="background-color: whitesmoke">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AroundTheClock", "Index", "CarStore", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    <li>@Html.ActionLink("QL Hãng Xe", "HangXe", "Admin")</li>
                    <li>@Html.ActionLink("QL Loại Xe", "LoaiXe", "Admin")</li>
                    <li>@Html.ActionLink("QL Sản Phẩm", "Xe", "Admin")</li>
                    <li>@Html.ActionLink("QL Khách Hàng", "KhachHang", "Admin")</li>
                    <li>@Html.ActionLink("QL Thể Loại Tin", "TheLoaiTin", "Admin")</li>
                    <li>@Html.ActionLink("QL Tin tức", "TinTuc", "Admin")</li>
                    <li>@Html.ActionLink("QL Đơn hàng", "DonHang", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>

    <div>
        @RenderBody()
    </div>



    <div class="container body-content">
        <hr />
        <footer>

            <p>&copy; @DateTime.Now.Year - ASP.NET Application - Nhóm 2</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>

Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/LTW.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="~/Content/assets/images/icons/favicon.ico" />
    <title>Website Bán Xe - AroundTheClock</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color: whitesmoke">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AroundTheClock", "Index", "CarStore", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Giới Thiệu", "About", "CarStore")</li>
                    <li>@Html.ActionLink("Liên Hệ", "Contact", "CarStore")</li>
                    <li>@Html.ActionLink("Tin Tức", "Index", "TinTuc")</li>
                    <li>@Html.ActionLink("Sản Phẩm", "Sanpham", "CarStore")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.Action("GioHangPartial", "GioHang")</li>
                    <li>@Html.ActionLink("Đăng Nhập", "Dangnhap", "KhachHang")</li>
                    <li>@Html.ActionLink("Đăng Ký", "Dangky", "KhachHang")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <br />
                <p class="lead">CÁC LOẠI XE</p>
                @Html.Action("Cacloaixe", "CarStore")
                <br />
                <p class="lead">HÃNG XE</p>
                @Html.Action("Hangxe", "CarStore")
            </div>
            <div class="col-md-9">
                <div class="row carousel-holder">
                    <div class="col-md-12">
                        <br />
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img class="slide-image" src="~/Content/images/banner1.jpg" alt="">

                                </div>
                                <div class="item">
                                    <img class="slide-image" src="~/Content/images/banner2.jpg" alt="">

                                </div>
                                <div class="item">
                                    <img class="slide-image" src="~/Content/images/banner3.jpg" alt="">

                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div>
                    @RenderBody()
                </div>

            </div>
        </div>
    </div>



    <div class="container body-content">
        <hr />
        <footer>

            <p>&copy; @DateTime.Now.Year - ASP.NET Application - Nhóm 2</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>

Views/Shared/_LayoutTinTuc.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- bootstrap css -->
    <link href="~/Content/TrangChu/css/bootstrap.min.css" rel="stylesheet" />
    <!-- style css -->
    <link href="~/Content/TrangChu/css/style.css" rel="stylesheet" />
    <!-- Responsive-->
    <link href="~/Content/TrangChu/css/responsive.css" rel="stylesheet" />
    <!-- Scrollbar Custom CSS -->
    <link href="~/Content/TrangChu/css/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">

    <link rel="stylesheet" href="~/Content/LTW.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="~/Content/assets/images/icons/favicon.ico" />
    <title>Website Bán Xe - AroundtheClock</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<!-- body -->
<body class="main-layout">
    <header>
        <!-- header inner -->
        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                        <div class="full">
                            <div class="center-desk">
                                <div class="logo">
                                    <a href="@Url.Action("Index","CarStore")"><img src="~/Content/TrangChu/images/logo2.png" alt="#" /></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                        <nav class="navigation navbar navbar-expand-md navbar-dark ">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarsExample04">
                                <ul class="navbar-nav mr-auto" style="padding-top:17.5px">
                                    <li class="nav-item">
                                        <a class="nav-link" href="@Url.Action("AboutUs","CarStore")">Giới Thiệu</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="@Url.Action("Contact","CarStore")">Liên Hệ</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="@Url.Action("IndexTinTuc","CarStore")">Tin Tức</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="@Url.Action("Sanpham","CarStore")">Sản Phẩm</a>
                                    </li>
                                </ul>
                                <ul class="navbar-nav mr-auto">
                                    <li class="nav-item">
                                        <div class="dropdown">
                                            <button class="dropbtn" style="">NGƯỜI DÙNG</button>
                                            <div class="dropdown-content">
                                                <a href="@Url.Action("Dangnhap","KhachHang")">Đăng Nhập</a>
                                                <a href="@Url.Action("Dangky","KhachHang")">Đăng Ký</a>
                                                @Html.Action("GioHangPartial", "GioHang")
                                            </div>
                                        </div>
                                    </li>
                                </ul>

                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- banner -->
    <div class="col-md-12">
        <div class="row carousel-holder">
            <div class="col-md-12">
                <br />
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img class="slide-image img-thumbnail" src="~/Content/images/banner7.jpg" alt="">
                            <h3 class="carousel-caption">Audi M8 V10</h3>
                        </div>
                        <div class="item">
                            <img class="slide-image img-thumbnail" src="~/Content/images/banner6.jpg" alt="">
                            <h3 class="carousel-caption">BMW E92 M3</h3>
                        </div>
                        <div class="item">
                            <img class="slide-image img-thumbnail" src="~/Content/images/banner5.jpg" alt="">
                            <h3 class="carousel-caption">Lamborghini Aventador</h3>
                        </div>
                        <div class="item">
                            <img class="slide-image img-thumbnail" src="~/Content/images/banner4.jpg" alt="">
                            <h3 class="carousel-caption">Lamborghini Veneno</h3>
                        </div>
                    </div>
                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>

        </div>
    </div>

    <!-- end banner -->
    <!-- car -->
    <div class="car">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="titlepage">
                        <h2>ĐA DẠNG VỀ LOẠI XE</h2>
                        <span>Website của chúng tôi chuyên cung cấp nhiều loại xe. Từ xe tải, xe con, xe du lịch đến các loại xe như xe máy và xe đạp,.. Bất cứ loại xe nào mà quý khách cần!</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 padding_leri">
                    <div class="car_box">
                        <figure><img src="~/Content/TrangChu/images/car_img1.png" alt="#" /></figure>
                        <h3>Hundai</h3>
                    </div>
                </div>
                <div class="col-sm-4 padding_leri">
                    <div class="car_box">
                        <figure><img src="~/Content/TrangChu/images/car_img2.png" alt="#" /></figure>
                        <h3>Audi</h3>
                    </div>
                </div>
                <div class="col-sm-4 padding_leri">
                    <div class="car_box">
                        <figure><img src="~/Content/TrangChu/images/car_img3.png" alt="#" /></figure>
                        <h3>BMW X5</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!---->
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <br />
                <p class="lead" style="text-align:center; color:black">TIN THEO THỂ LOẠI</p>
                @Html.Action("Theloaitin", "CarStore")
            </div>
            <div class="col-md-9">


                <div>
                    @RenderBody()
                </div>

            </div>
        </div>
    </div>
    <!-- end car -->
    <footer>
        <div class="footer">
            <div class="copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <p>@DateTime.Now.Year - ASP.NET Application - Nhóm 2 - 19DTHA5</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Javascript files-->
    <script src="~/Content/TrangChu/js/jquery.min.js"></script>
    <script src="~/Content/TrangChu/js/popper.min.js"></script>
    <script src="~/Content/TrangChu/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/TrangChu/js/jquery-3.0.0.min.js"></script>
    <script src="~/Content/TrangChu/js/plugin.js"></script>
    <!-- sidebar -->
    <script src="~/Content/TrangChu/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/Content/TrangChu/js/custom.js"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
</body>
</html>