Controllers/KhachHangController.cs
using Nhom2_WebsiteBanXe.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nhom2_WebsiteBanXe.Controllers
{
    public class KhachHangController : Controller
    {
        DataClasses1DataContext data = new DataClasses1DataContext();
        // GET: KhachHang
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["HoTenKH"];
            var gioitinh = collection["GioitinhKH"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["NgaySinh"]);
            var sdt = collection["SdtKH"];
            var diachi = collection["DiachiKH"];
            var email = collection["eMailKH"];
            var tendangnhap = collection["TendangnhapKH"];
            //var matkhau = collection["MatkhauKH"];
            //mã hóa MD5
            var matkhau = MaHoa.GetMD5(collection["MatkhauKH"]);
            //
            var matkhaunl = collection["Matkhaunl"];
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên không được để trống";
            }
            else if (String.IsNullOrEmpty(gioitinh))
            {
                ViewData["Loi2"] = "Giới tính không được để trống";
            }
            else if (String.IsNullOrEmpty(sdt))
            {
                ViewData["Loi3"] = "Số điện thoại không được để trống";
            }
            else if (String.IsNullOrEmpty(diachi))
            {
                ViewData["Loi4"] = "Địa chỉ không được để trống";
            }
            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Email không được để trống";
            }
            else if (String.IsNullOrEmpty(tendangnhap))
            {
                ViewData["Loi6"] = "Tên đăng nhập không được để trống";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi7"] = "Mật khẩu không được để trống";
            }
            else if (String.IsNullOrEmpty(sdt))
            {
                ViewData["Loi8"] = "Vui lòng nhập lại mật khẩu";
            }
            else
            {
                kh.HoTen = hoten;
                kh.GioiTinh = gioitinh;
                kh.NgaySinh = DateTime.Parse(ngaysinh);
                kh.SDT = sdt;
                kh.DiaChi = diachi;
                kh.eMail = email;
                kh.TaiKhoan = tendangnhap;
                //kh.MatKhau = matkhau;
                kh.MatKhau = MaHoa.GetMD5(matkhau);
                //
                data.KhachHangs.InsertOnSubmit(kh);
                data.SubmitChanges();
                return RedirectToAction("Dangnhap");
            }
            return this.Dangky();
        }

        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            var tendn = collection["TendangnhapKH"];
            //var mk = collection["MatkhauKH"];
            var mk = MaHoa.GetMD5(collection["MatkhauKH"]);
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Vui lòng nhập Tài khoản";
            }
            else if (String.IsNullOrEmpty(mk))
            {
                ViewData["Loi2"] = "Vui lòng nhập Mật khẩu";
            }
            else
            {
                KhachHang kh = data.KhachHangs.SingleOrDefault(n => n.TaiKhoan == tendn && n.MatKhau == MaHoa.GetMD5(mk));
                if (kh != null)
                {
                    Session["TaiKhoan"] = kh;
                    return RedirectToAction("Index", "CarStore");
                }
                else
                    ViewBag.Thongbao = "Sai tài khoản hoặc mật khẩu";
            }
            return View();
        }
    }
}

Views/KhachHang/Dangky.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Đăng ký thành viên</title>

    <!-- Font Icon -->
    <link href="~/Content/assets2/fonts/material-icon/css/material-design-iconic-font.min.css" rel="stylesheet" />
    <!-- Main css -->
    <link href="~/Content/assets2/css/style.css" rel="stylesheet" />
</head>
<body>

    <div class="main">

        <!-- Sign up form -->
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        @using (Html.BeginForm())
                        {
                            @Html.ValidationSummary(true)
                            <h2 class="form-title">ĐĂNG KÝ</h2>
                            <form method="POST" class="register-form" id="register-form">
                                <div class="form-group">
                                    <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                    <input type="text" name="HoTenKH" id="name" placeholder="Họ và tên" />
                                </div>
                                <div class="form-group">
                                    <label for="gioitinh"><i class="zmdi zmdi-male-female material-icons-name"></i></label>
                                    <input type="text" name="GioitinhKH" id="name" placeholder="Giới tính" />
                                </div>
                                <div class="form-group">
                                    <label for="dob"><i class="zmdi zmdi-calendar material-icons-name"></i></label>
                                    <input type="date" name="NgaySinh" id="name" placeholder="Ngày sinh" />
                                </div>
                                <div class="form-group">
                                    <label for="sdt"><i class="zmdi zmdi-phone material-icons-name"></i></label>
                                    <input type="text" name="SdtKH" id="email" placeholder="Phone" />
                                </div>
                                <div class="form-group">
                                    <label for="diachi"><i class="zmdi zmdi-pin-drop material-icons-name"></i></label>
                                    <input type="text" name="DiachiKH" id="name" placeholder="Địa chỉ" />
                                </div>
                                <div class="form-group">
                                    <label for="sdt"><i class="zmdi zmdi-email"></i></label>
                                    <input type="text" name="eMailKH" id="email" placeholder="Email" />
                                </div>
                                <div class="form-group">
                                    <label for="taikhoan"><i class="zmdi zmdi-account-box material-icons-name"></i></label>
                                    <input type="text" name="TendangnhapKH" id="name" placeholder="Tài khoản" />
                                </div>
                                <div class="form-group">
                                    <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                    <input type="password" name="MatkhauKH" id="pass" placeholder="Mật khẩu" />
                                </div>
                                <div class="form-group">
                                    <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                    <input type="password" name="Matkhaunl" id="re_pass" placeholder="Nhập lại mật khẩu" />
                                </div>
                                <div class="form-group form-button">
                                    <input type="submit" id="signup" class="form-submit" value="Register" />
                                </div>
                            </form>
                        }

                    </div>
                    <div class="signup-image">
                        <figure><img src="~/Content/assets2/images/signup-image.jpg" alt="sing up image"></figure>
                        <a href="@Url.Action("Dangnhap","KhachHang")" class="signup-image-link">TÔI ĐÃ LÀ THÀNH VIÊN</a>
                        <a href="@Url.Action("Index","CarStore")" class="signup-image-link">TRỞ VỀ TRANG CHỦ</a>
                    </div>
                </div>
            </div>
        </section>

    </div>
    <div class="container body-content">
        <hr />
        <footer>

            <p>&copy; @DateTime.Now.Year - ASP.NET Application - Nhóm 2</p>
        </footer>
    </div>

    <!-- JS -->
    <script src="~/Content/assets2/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/assets2/js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>





@*<h2 style="text-align:center">ĐĂNG KÝ THÀNH VIÊN</h2>
<br />
<table align="center">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <tr style="height:40px">
            <td>Họ tên: </td>
            <td>
                @Html.TextBox("HotenKH")
                @ViewData["Loi1"]
            </td>
        </tr>
        <tr style="height:40px">
            <td>Giới tính: </td>
            <td>
                @Html.TextBox("GioitinhKH")
                @ViewData["Loi2"]
            </td>
        </tr>
        <tr style="height:40px">
            <td>Ngày sinh: </td>
            <td>
                <input type="date" name="NgaySinh" />
            </td>
        </tr>
        <tr style="height:40px">
            <td>SĐT: </td>
            <td>
                @Html.TextBox("SdtKH")
                @ViewData["Loi3"]
            </td>
        </tr>
        <tr style="height:40px">
            <td>Địa chỉ: </td>
            <td>
                @Html.TextBox("DiachiKH")
                @ViewData["Loi4"]
            </td>
        </tr>
        <tr style="height:40px">
            <td>eMail: </td>
            <td>
                @Html.TextBox("eMailKH")
                @ViewData["Loi5"]
            </td>
        </tr>
        <tr style="height:40px">
            <td>Tên đăng nhập: </td>
            <td>
                @Html.TextBox("TendangnhapKH")
                @ViewData["Loi6"]
            </td>
        </tr>
        <tr style="height:40px">
            <td>Mật khẩu: </td>
            <td>
                @Html.Password("MatkhauKH")
                @ViewData["Loi7"]
            </td>
        </tr>
        <tr style="height:40px">
            <td>Nhập lại mật khẩu: </td>
            <td>
                @Html.Password("Matkhaunl")
                @ViewData["Loi8"]
            </td>
        </tr>
        <tr style="height:40px">
            <td></td>
            <td>
                <input type="submit" value="Đăng ký" />
            </td>
        </tr>
    }
</table>*@

Views/KhachHang/Dangnhap.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Đăng nhập</title>

    <!-- Font Icon -->
    <link href="~/Content/assets2/fonts/material-icon/css/material-design-iconic-font.min.css" rel="stylesheet" />
    <!-- Main css -->
    <link href="~/Content/assets2/css/style.css" rel="stylesheet" />
</head>
<body>
    <div class="main">

        <!-- Sing in  Form -->
        <section class="sign-in">

            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="~/Content/assets2/images/signin-image.jpg" alt="sing up image"></figure>
                        <a href="@Url.Action("Dangky","KhachHang")" class="signup-image-link">ĐĂNG KÝ THÀNH VIÊN</a>
                        <a href="@Url.Action("Index","CarStore")" class="signup-image-link">TRỞ VỀ TRANG CHỦ</a>
                    </div>
                    <div class="signin-form">
                        @using (Html.BeginForm())
                        {
                            @Html.ValidationSummary(true)
                            <h2 class="form-title">ĐĂNG NHẬP</h2>
                            <h4 style="color:red; text-align:center">@ViewBag.Thongbao</h4>
                            <form method="POST" class="register-form" id="login-form">
                                <div class="form-group">
                                    <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                    <input type="text" name="TendangnhapKH" id="your_name" placeholder="Username" />
                                </div>
                                @ViewData["Loi1"]
                                <div class="form-group">
                                    <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                    <input type="password" name="MatkhauKH" id="your_pass" placeholder="Password" />
                                </div>
                                @ViewData["Loi2"]
                                <div class="form-group form-button">
                                    <input type="submit" name="signin" id="signin" class="form-submit" value="Log in" />
                                </div>
                            </form>
                        }
                        <div class="social-login">
                            <span class="social-label">Đăng nhập bằng</span>
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </section>

    </div>
    <div class="container body-content">
        <hr />
        <footer>

            <p>&copy; @DateTime.Now.Year - ASP.NET Application - Nhóm 2</p>
        </footer>
    </div>

    <!-- JS -->
    <script src="~/Content/assets2/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/assets2/js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>